--------------------------------------------------------
--  File created - Friday-April-07-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PHYS
--------------------------------------------------------

  CREATE TABLE "TOLIVE"."PHYS_NEW" 
   (	"PDATE" DATE, 
	"SHIFT" NUMBER, 
	"S2BT12" NUMBER(3,1), 
	"S2BT14" NUMBER(3,1), 
	"S2AT14" NUMBER(3,1), 
	"S2AT28" NUMBER(3,1), 
	"S2COMP" NUMBER, 
	"S2LCOMP" NUMBER(3,1), 
	"S3BT12" NUMBER(3,1), 
	"S3BT14" NUMBER(3,1), 
	"S3AT14" NUMBER(3,1), 
	"S3AT28" NUMBER(3,1), 
	"S3COMP" NUMBER, 
	"S3LCOMP" NUMBER(3,1), 
	"S2BT916" NUMBER(3,1), 
	"S3BT916" NUMBER(3,1), 
	"S2LCMP3" NUMBER(3,1), 
	"S3LCMP3" NUMBER(3,1)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 2097152 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BUILD" ;

   COMMENT ON COLUMN "TOLIVE"."PHYS_NEW."PDATE" IS 'Shift Date';
   COMMENT ON COLUMN "TOLIVE"."PHYS_NEW"."SHIFT" IS 'Shift Number';
   COMMENT ON COLUMN "TOLIVE"."PHYS_NEW"."S2BT12" IS 'Step 2 BT Cum +1/2 inch screen %';
   COMMENT ON COLUMN "TOLIVE"."PHYS_NEW"."S2BT14" IS 'Step 2 BT Cum +1/4 inch screen %';
   COMMENT ON COLUMN "TOLIVE"."PHYS_NEW"."S2AT14" IS 'Step 2 AT Cum +1/4 inch screen %';
   COMMENT ON COLUMN "TOLIVE"."PHYS_NEW"."S2AT28" IS 'Step 2 AT -28 mesh %';
   COMMENT ON COLUMN "TOLIVE"."PHYS_NEW"."S3BT12" IS 'Step 3 BT Cum +1/2 inch screen %';
   COMMENT ON COLUMN "TOLIVE"."PHYS_NEW"."S3BT14" IS 'Step 3 BT Cum +1/4 inch screen %';
   COMMENT ON COLUMN "TOLIVE"."PHYS_NEW"."S3AT14" IS 'Step 3 AT Cum +1/4 inch screen %';
   COMMENT ON COLUMN "TOLIVE"."PHYS_NEW"."S3AT28" IS 'Step 3 AT -28 mesh %';
   COMMENT ON COLUMN "TOLIVE"."PHYS_NEW"."S2BT916" IS 'Step 2 BT Cum +9/16 inch screen %';
   COMMENT ON COLUMN "TOLIVE"."PHYS_NEW"."S3BT916" IS 'Step 3 BT Cum +9/16 inch screen %';
   COMMENT ON TABLE "TOLIVE"."PHYS_NEW"  IS 'Table used to give pellet physicals values';
  GRANT UPDATE ON "TOLIVE"."PHYS_NEW" TO "R_TOLIVE_APP";
  GRANT SELECT ON "TOLIVE"."PHYS_NEW" TO "R_TOLIVE_APP";
  GRANT INSERT ON "TOLIVE"."PHYS_NEW" TO "R_TOLIVE_APP";
  GRANT DELETE ON "TOLIVE"."PHYS_NEW" TO "R_TOLIVE_APP";
  GRANT SELECT ON "TOLIVE"."PHYS_NEW" TO "R_TOLIVE_SELECT";
  GRANT SELECT ON "TOLIVE"."PHYS_NEW" TO "VIEW_ONLY";
